### ISSUE TITLE
Is there a Python 3 version?

### ISSUE THREAD

**Issue by reed9999** [qixingyue/qapp#1]
In trying to install with virtualenv with an Anaconda Python 3.6 installation I get: 

```
Collecting qapp
  Downloading qapp-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\reed9\AppData\Local\Temp\pip-build-yxj5llyx\qapp\setup.py", line 5, in <module>
        import qapp
      File "C:\Users\reed9\AppData\Local\Temp\pip-build-yxj5llyx\qapp\qapp\__init__.py", line 16
        print "python -m qapp.skel"
                                  ^
    SyntaxError: Missing parentheses in call to 'print'

```
Apparently this is standard for Python 2 print statements needing to be print() calls in Python 3. I can't tell from the documentation here; is qapp compatible with Python 3? If I just hand hack the print statement, is there any problem that might cause downstream?

**Comment by qixingyue** [comment]
Sorry this is only used python2. But print must used like this 

print（）
